import React, { useState } from 'react'
import {
  ShieldCheck,
  ShieldAlert,
  Shield,
  AlertTriangle,
  CheckCircle2,
  AlertCircle,
  Copy,
  Check,
  X,
  ExternalLink,
} from 'lucide-react'
import type { SecurityAuditReport } from '../types'

interface SecurityReportModalProps {
  report: SecurityAuditReport
  onClose: () => void
}

export const SecurityReportModal: React.FC<SecurityReportModalProps> = ({ report, onClose }) => {
  const [copied, setCopied] = useState(false)

  const isLow = report.risk_level === 'low'
  const isMed = report.risk_level === 'medium'
  const isHigh = report.risk_level === 'high'
  const isCrit = report.risk_level === 'critical'

  const badgeBg = isLow ? '#e6f4ea' : isMed ? '#fef7e0' : isHigh ? '#fff0d4' : '#fce8e6'
  const badgeColor = isLow ? '#137333' : isMed ? '#b06000' : isHigh ? '#e37400' : '#c5221f'
  const badgeBorder = isLow ? '#ceead6' : isMed ? '#feefc3' : isHigh ? '#ffdfb0' : '#fad2cf'

  const handleCopyMarkdown = () => {
    const md = [
      `# API Relay Security Audit Report`,
      `**Model ID:** ${report.model_id}`,
      `**Endpoint:** ${report.endpoint}`,
      `**Provider Protocol:** ${report.provider_type}`,
      `**Audit Date:** ${new Date(report.audited_at).toLocaleString()}`,
      `**Risk Level:** ${report.risk_level.toUpperCase()} (Risk Score: ${report.risk_score}/100)`,
      '',
      `## Executive Summary`,
      report.summary,
      '',
      `## Probe Results`,
      ...report.probes.map(
        (p) =>
          `- [${p.status.toUpperCase()}] **${p.name}** (${p.category}): ${p.details}${
            p.evidence ? `\n  - *Evidence:* \`${p.evidence}\`` : ''
          }`
      ),
      '',
      `## Remediation Recommendations`,
      ...report.recommendations.map((r) => `1. ${r}`),
      '',
      `*Generated by Antigravity Swiss Knife Security Audit Engine (inspired by api-relay-audit)*`,
    ].join('\n')

    navigator.clipboard.writeText(md)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div
      style={{
        position: 'fixed',
        inset: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        backdropFilter: 'blur(3px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 1100,
      }}
      onClick={onClose}
    >
      <div
        className="google-card"
        style={{
          width: '680px',
          maxWidth: '94vw',
          maxHeight: '90vh',
          overflowY: 'auto',
          padding: '28px',
          backgroundColor: '#ffffff',
          boxShadow: 'var(--shadow-lg)',
          display: 'flex',
          flexDirection: 'column',
          gap: '20px',
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: '16px' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
              <Shield size={20} color="var(--primary)" />
              <h2 style={{ margin: 0, fontSize: '18px', fontWeight: 700, color: 'var(--text)' }}>
                API Relay Security Audit Report
              </h2>
            </div>
            <div style={{ fontSize: '12px', color: 'var(--text-muted)' }}>
              Inspecting endpoint lineage, prompt integrity, canary signatures, and leakage vectors.
            </div>
          </div>
          <button
            onClick={onClose}
            className="btn-pill-tonal"
            style={{ padding: '6px' }}
            title="Close"
          >
            <X size={16} />
          </button>
        </div>

        {/* Top Risk Score Banner */}
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            padding: '16px 20px',
            borderRadius: '12px',
            backgroundColor: badgeBg,
            border: `1.5px solid ${badgeBorder}`,
            gap: '16px',
            flexWrap: 'wrap',
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
            {isLow ? (
              <ShieldCheck size={36} color={badgeColor} />
            ) : isCrit ? (
              <ShieldAlert size={36} color={badgeColor} />
            ) : (
              <AlertTriangle size={36} color={badgeColor} />
            )}
            <div>
              <div
                style={{
                  fontSize: '11px',
                  fontWeight: 700,
                  color: badgeColor,
                  letterSpacing: '0.8px',
                  textTransform: 'uppercase',
                }}
              >
                Overall Risk Assessment
              </div>
              <div style={{ fontSize: '20px', fontWeight: 800, color: badgeColor, marginTop: '2px' }}>
                {report.risk_level.toUpperCase()} RISK
              </div>
            </div>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '4px' }}>
            <div style={{ fontSize: '12px', fontWeight: 700, color: badgeColor }}>
              Risk Score: {report.risk_score} / 100
            </div>
            {/* Visual Risk Progress Bar */}
            <div
              style={{
                width: '140px',
                height: '8px',
                borderRadius: '4px',
                backgroundColor: 'rgba(0, 0, 0, 0.1)',
                overflow: 'hidden',
              }}
            >
              <div
                style={{
                  width: `${report.risk_score}%`,
                  height: '100%',
                  backgroundColor: badgeColor,
                  borderRadius: '4px',
                  transition: 'width 0.4s ease',
                }}
              />
            </div>
            <div style={{ fontSize: '10px', color: badgeColor, opacity: 0.85 }}>
              {isLow ? 'Clean & Trusted' : isMed ? 'Advisory Notice' : isHigh ? 'Elevation Warning' : 'Critical Danger'}
            </div>
          </div>
        </div>

        {/* Metadata Grid */}
        <div
          style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(190px, 1fr))',
            gap: '10px',
            backgroundColor: 'var(--canvas)',
            padding: '12px 16px',
            borderRadius: '10px',
            border: '1px solid var(--border)',
            fontSize: '12px',
          }}
        >
          <div>
            <span style={{ color: 'var(--text-muted)', display: 'block', fontSize: '11px' }}>ENDPOINT URL:</span>
            <span style={{ fontWeight: 600, color: 'var(--text)', wordBreak: 'break-all', fontFamily: 'monospace' }}>
              {report.endpoint}
            </span>
          </div>
          <div>
            <span style={{ color: 'var(--text-muted)', display: 'block', fontSize: '11px' }}>MODEL IDENTIFIER:</span>
            <span style={{ fontWeight: 600, color: 'var(--text)', fontFamily: 'monospace' }}>
              {report.model_id}
            </span>
          </div>
          <div>
            <span style={{ color: 'var(--text-muted)', display: 'block', fontSize: '11px' }}>AUDITED TIMESTAMP:</span>
            <span style={{ fontWeight: 600, color: 'var(--text)' }}>
              {new Date(report.audited_at).toLocaleTimeString()}
            </span>
          </div>
        </div>

        {/* Summary Description */}
        <div
          style={{
            fontSize: '13px',
            color: 'var(--text)',
            lineHeight: 1.5,
            padding: '12px 16px',
            borderRadius: '8px',
            backgroundColor: '#f8fafc',
            borderLeft: `4px solid ${badgeColor}`,
          }}
        >
          {report.summary}
        </div>

        {/* Probes Breakdown List */}
        <div>
          <div
            style={{
              fontSize: '12px',
              fontWeight: 700,
              color: 'var(--text-muted)',
              textTransform: 'uppercase',
              letterSpacing: '0.6px',
              marginBottom: '10px',
            }}
          >
            Security Probes Breakdown ({report.probes.length} Tests)
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
            {report.probes.map((probe) => {
              const pPassed = probe.status === 'passed'
              const pWarn = probe.status === 'warning'
              const statusBg = pPassed ? '#e6f4ea' : pWarn ? '#fef7e0' : '#fce8e6'
              const statusColor = pPassed ? '#137333' : pWarn ? '#b06000' : '#c5221f'

              return (
                <div
                  key={probe.id}
                  style={{
                    border: '1px solid var(--border-subtle)',
                    borderRadius: '8px',
                    padding: '12px 14px',
                    backgroundColor: '#ffffff',
                    display: 'flex',
                    flexDirection: 'column',
                    gap: '4px',
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '8px' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                      {pPassed ? (
                        <CheckCircle2 size={16} color="var(--green)" />
                      ) : pWarn ? (
                        <AlertCircle size={16} color="#b06000" />
                      ) : (
                        <AlertTriangle size={16} color="#c5221f" />
                      )}
                      <span style={{ fontSize: '13px', fontWeight: 700, color: 'var(--text)' }}>
                        {probe.name}
                      </span>
                      <span
                        style={{
                          fontSize: '10px',
                          color: 'var(--text-muted)',
                          backgroundColor: 'var(--tonal)',
                          padding: '1px 6px',
                          borderRadius: '4px',
                        }}
                      >
                        {probe.category}
                      </span>
                    </div>

                    <span
                      style={{
                        fontSize: '10px',
                        fontWeight: 700,
                        backgroundColor: statusBg,
                        color: statusColor,
                        padding: '2px 8px',
                        borderRadius: '10px',
                        textTransform: 'uppercase',
                      }}
                    >
                      {probe.status}
                    </span>
                  </div>

                  <div style={{ fontSize: '12px', color: 'var(--text)', marginTop: '2px' }}>
                    {probe.details}
                  </div>

                  {probe.evidence && (
                    <div
                      style={{
                        fontSize: '11px',
                        fontFamily: 'monospace',
                        color: 'var(--text-muted)',
                        backgroundColor: 'var(--canvas)',
                        padding: '4px 8px',
                        borderRadius: '4px',
                        marginTop: '4px',
                      }}
                    >
                      Evidence: {probe.evidence}
                    </div>
                  )}
                </div>
              )
            })}
          </div>
        </div>

        {/* Recommendations */}
        <div
          style={{
            backgroundColor: '#f8fafc',
            border: '1px solid var(--border)',
            borderRadius: '10px',
            padding: '14px 18px',
          }}
        >
          <div style={{ fontSize: '12px', fontWeight: 700, color: 'var(--text)', marginBottom: '8px' }}>
            Recommended Action Items:
          </div>
          <ul style={{ margin: 0, paddingLeft: '20px', fontSize: '12px', color: 'var(--text-muted)', display: 'flex', flexDirection: 'column', gap: '4px' }}>
            {report.recommendations.map((rec, i) => (
              <li key={i}>{rec}</li>
            ))}
          </ul>
        </div>

        {/* Footer Actions */}
        <div
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            borderTop: '1px solid var(--border)',
            paddingTop: '16px',
          }}
        >
          <button
            onClick={handleCopyMarkdown}
            className="btn-pill-tonal"
            style={{
              padding: '6px 14px',
              fontSize: '12px',
              display: 'inline-flex',
              alignItems: 'center',
              gap: '6px',
            }}
          >
            {copied ? <Check size={14} color="var(--green)" /> : <Copy size={14} />}
            <span>{copied ? 'Copied to Clipboard!' : 'Copy Markdown Report'}</span>
          </button>

          <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
            <a
              href="https://github.com/toby-bridges/api-relay-audit"
              target="_blank"
              rel="noreferrer"
              style={{
                fontSize: '11px',
                color: 'var(--primary)',
                display: 'inline-flex',
                alignItems: 'center',
                gap: '4px',
                textDecoration: 'none',
                marginRight: '8px',
              }}
            >
              <span>api-relay-audit Project</span>
              <ExternalLink size={11} />
            </a>

            <button onClick={onClose} className="btn-pill-primary" style={{ padding: '6px 18px', fontSize: '12px' }}>
              Done
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
